server:
  ingress:
    enabled: true
    className: ""
    annotations: {
      cert-manager.io/cluster-issuer: letsencrypt-prod,
      kubernetes.io/ingress.class: nginx,
      kubernetes.io/tls-acme: "true",
      nginx.ingress.kubernetes.io/ssl-passthrough: "true",
      # If you encounter a redirect loop or are getting a 307 response code
      # then you need to force the nginx ingress to connect to the backend using HTTPS.
      #
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      }
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - argo.week9challenge.tk
    paths:
      - /
    pathType: Prefix
    tls: 
      - secretName: argo-week9challenge-tls
        hosts:
        - argo.week9challenge.tk
    https: true
  extraArgs:
    - --insecure