
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: aHZzLjlGSU5OS20xc1IyR0RtTHhvdDQ5YnB6Tg== # "root"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
